<?xml version="1.0"?>

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Body Dimensions -->
    <xacro:property name="body_link_x_dim" value="1"/>
    <xacro:property name="body_link_y_dim" value="0.6"/>
    <xacro:property name="body_link_z_dim" value="0.3"/>

    <!-- Wheel Dimensions -->
    <xacro:property name="wheel_link_radius" value="0.15"/>
    <xacro:property name="wheel_link_length" value="0.1"/>
    <xacro:property name="wheel_link_z_location" value="-0.1"/>

    <!-- Material Density -->
    <xacro:property name="body_density" value="2710.0"/>
    <xacro:property name="wheel_density" value="2710.0"/>

    <!-- Pi -->
    <xacro:property name="pi_constant" value="3.1415926"/>

    <!-- Robot Body and Wheel Weight -->
    <xacro:property name="body_mass" value="${body_density * body_link_x_dim * body_link_y_dim * body_link_z_dim}"/>
    <xacro:property name="wheel_mass" value="${wheel_density * pi_constant * wheel_link_radius * wheel_link_radius * wheel_link_length}"/>

    <!-- Moments -->
    <xacro:property name="Iz_wheel" value="${0.5 * wheel_mass * wheel_link_radius * wheel_link_radius}"/>
    <xacro:property name="Ixy_wheel" value="${(1.0)/(12.0)*wheel_mass * (3.0 * wheel_link_radius * wheel_link_radius + wheel_link_length * wheel_link_length)}"/>

    <xacro:macro name="inertia_wheel">
        <inertial>
            <origin xyz = "0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${Ixy_wheel}"  iyy="${Ixy_wheel}"  izz="${Iz_wheel}" ixy="0.0" ixz="0.0" iyz="0.0"/>
        </inertial>
    </xacro:macro>

    <!-- <xacro:include filename="$(find amiga_description)/urdf/amiga.new.gazebo"/> -->

    <!-- define the base link -->
    <link name="dummy"/>
    <joint name="dummy_joint" type="fixed">
        <parent link="dummy"/>
        <child link="body_link"/>
    </joint>

    <link name="body_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${body_mass}"/>
            <inertia    ixx="${(1.0)/(12.0)*body_mass*(body_link_y_dim * body_link_y_dim + body_link_z_dim * body_link_z_dim)}"
                        iyy="${(1.0)/(12.0)*body_mass*(body_link_x_dim * body_link_x_dim + body_link_z_dim * body_link_z_dim)}"
                        izz="${(1.0)/(12.0)*body_mass*(body_link_y_dim * body_link_y_dim + body_link_x_dim * body_link_x_dim)}"
                        ixy="0"
                        ixz="0"
                        iyz="0"/>
        </inertial>
    </link>

    <joint name="wheel1_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel1_link"/>
        <origin xyz="${-body_link_x_dim/2.0 + 1.2*wheel_link_radius} ${-body_link_y_dim/2.0 - wheel_link_length/2.0} ${wheel_link_z_location}" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamic damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel1_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertia_wheel/>
    </link>

    <joint name="wheel2_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel2_link"/>
        <origin xyz="${-body_link_x_dim/2.0 + 1.2*wheel_link_radius} ${body_link_y_dim/2.0 + wheel_link_length/2.0} ${wheel_link_z_location}" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamic damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel2_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertia_wheel/>
    </link>


    <joint name="wheel3_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel3_link"/>
        <origin xyz="${body_link_x_dim/2.0 - 1.2*wheel_link_radius} ${-body_link_y_dim/2.0 - wheel_link_length/2.0} ${wheel_link_z_location}" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamic damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel3_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertia_wheel/>
    </link>

    <joint name="wheel4_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel4_link"/>
        <origin xyz="${body_link_x_dim/2.0 - 1.2*wheel_link_radius} ${body_link_y_dim/2.0 + wheel_link_length/2.0} ${wheel_link_z_location}" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamic damping="1.0" friction="1.0"/>
    </joint>
    <link name="wheel4_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi_constant/2.0} 0 0" />
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertia_wheel/>
    </link>



    <transmission name="trans_wheel1_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wheel1_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wheel1_joint_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


    <transmission name="trans_wheel2_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wheel2_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wheel2_joint_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_wheel3_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wheel3_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wheel3_joint_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_wheel4_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wheel4_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wheel4_joint_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
</robot>