amiga_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

amiga_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['wheel_0_joint', 'wheel_1_joint']
  right_wheel: ['wheel_2_joint', 'wheel_3_joint'] 
  publish_rate: 50
  pose_covariance_diagonal:   [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal:  [0.001, 0.001, 0.001,     1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  k_l: 0.1
  k_r: 0.1

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 2.1 # default: 1.0
  wheel_radius_multiplier    : 0.47 # default: 1.0
  wheel_radius: 0.45

  wheel_separation : 2.0 #Distance between left and right
  # wheel_radius : 0.1651

  # Base frame_id
  base_frame_id: base_link
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 20.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2

