amiga_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

amiga_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['wheel_0_joint', 'wheel_1_joint']
  right_wheel: ['wheel_2_joint', 'wheel_3_joint'] 
  publish_rate: 50
  pose_covariance_diagonal:   [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal:  [0.001, 0.001, 0.001,     1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.1  # Brake if cmd_vel has timeout:

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0
  wheel_radius: 0.215 #  RADIUS !!!!!!
  wheel_separation : 2.0 #Distance between left and right

  # 0.2 -> 1.08
  # 0.25 -> 0.86
  # 0.05 -> delta = 0.22
  # (0.25 - 0.14/0.22 * 0.05) <- 1.00
  k_l: 0.5
  k_r: 0.5

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true


  # wheel_radius : 0.1651

  # Base frame_id
  base_frame_id: base_link
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 10.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 10.0   # rad/s^2

